export const RELATIVE_ROUTES = {
  TEMPLATE: 'template',
  COLOR: 'color',
  BUTTON: 'button',
  INPUT: 'input',
};

export const ABSOLUTE_ROUTES_FROM_PARENT = {
  TEMPLATE: (child: string) => `${RELATIVE_ROUTES.TEMPLATE}/${child}`,
};

export const ABSOLUTE_ROUTES = {
  COLOR: ABSOLUTE_ROUTES_FROM_PARENT.TEMPLATE(RELATIVE_ROUTES.COLOR),
  BUTTON: ABSOLUTE_ROUTES_FROM_PARENT.TEMPLATE(RELATIVE_ROUTES.BUTTON),
  INPUT: ABSOLUTE_ROUTES_FROM_PARENT.TEMPLATE(RELATIVE_ROUTES.INPUT),
};
