export const APP_HOTKEY = {
    MASTER: 'CTRL',
    DELETE: 'D',

    LOGIN_BUTTON: 'L',
    LOGOUT_BUTTON: 'L',
    OPEN_URL_BUTTON: 'O',

    TEMPLATE_PRIMARY_BUTTON: 'P',
    TEMPLATE_SECONDARY_BUTTON: 'S',
    TEMPLATE_ACCENT_BUTTON: 'A',
    TEMPLATE_DESTRUCTIVE_BUTTON: 'D',
};
