export const APP_HOTKEY = {
    MASTER: 'CTRL',
    DELETE: 'D',

    LOGIN_BUTTON: 'L',
    LOGOUT_BUTTON: 'L',
    OPEN_URL_BUTTON: 'O',
    ADD_NEW_LINK_INTO_GROUP_LINK_BUTTON: 'A',
    CREATE_LINK: 'R',
    CANCEL_CREATE_LINK: 'C',

    TEMPLATE_PRIMARY_BUTTON: 'P',
    TEMPLATE_SECONDARY_BUTTON: 'S',
    TEMPLATE_ACCENT_BUTTON: 'A',
    TEMPLATE_DESTRUCTIVE_BUTTON: 'D',
};
