export const RELATIVE_ROUTES = {
    USER: 'user',
    LOGIN: 'login',
    LOGOUT: 'logout',
    SIGN_IN: 'sign-in',
    RECOVERY: 'recovery',

    TEMPLATE: 'template',
    COLOR: 'color',
    BUTTON: 'button',
    INPUT: 'input',
};

export const ABSOLUTE_ROUTES_FROM_PARENT = {
    USER: (child: string) => `${RELATIVE_ROUTES.USER}/${child}`,
    TEMPLATE: (child: string) => `${RELATIVE_ROUTES.TEMPLATE}/${child}`,
};

export const ABSOLUTE_ROUTES = {
    LOGIN: ABSOLUTE_ROUTES_FROM_PARENT.USER(RELATIVE_ROUTES.LOGIN),
    LOGOUT: ABSOLUTE_ROUTES_FROM_PARENT.USER(RELATIVE_ROUTES.LOGOUT),
    SIGN_IN: ABSOLUTE_ROUTES_FROM_PARENT.USER(RELATIVE_ROUTES.SIGN_IN),
    RECOVERY: ABSOLUTE_ROUTES_FROM_PARENT.USER(RELATIVE_ROUTES.RECOVERY),

    COLOR: ABSOLUTE_ROUTES_FROM_PARENT.TEMPLATE(RELATIVE_ROUTES.COLOR),
    BUTTON: ABSOLUTE_ROUTES_FROM_PARENT.TEMPLATE(RELATIVE_ROUTES.BUTTON),
    INPUT: ABSOLUTE_ROUTES_FROM_PARENT.TEMPLATE(RELATIVE_ROUTES.INPUT),
};
